SET SERVEROUTPUT ON 
BEGIN 

    EXECUTE IMMEDIATE 'CREATE INDEX  CPI.DEF_POLICY_NO_IDX6 ON CPI.GIAC_DEFERRED_COMM_INCOME (YEAR,mm,iss_cd,line_cd,acct_trty_type,ri_cd)';
    
   
 DBMS_OUTPUT.PUT_LINE('index created');
EXCEPTION 
WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE(SQLERRM || '-' || SQLCODE);
END;
 /