SET SERVEROUTPUT ON

BEGIN
   EXECUTE IMMEDIATE
      ('ALTER TABLE cpi.GIPI_INSP_DATA DROP COLUMN DATE_REPORTED');

   DBMS_OUTPUT.PUT_LINE (
      'Successfully dropped DATE_REPORTED column to GIPI_INSP_DATA table.');
EXCEPTION
   WHEN OTHERS THEN
      DBMS_OUTPUT.put_line ('ERROR: ' || SQLERRM);
END;