var objPackQuoteList = null; // object that holds list of quotations under package quotation
var objPackQuoteLines = null;
var objPackQuoteItemList = null;
var objPackQuoteItemPerilList = null;
var objPackQuoteDeductiblesList = null;
var objPackQuoteMortgageeList = null;
var objPackQuoteInvoiceList = null;
var objCurrPackQuote = null;
var objDefaultCurrency = null;
var quotePerilChangeTag = 0;