SET SERVEROUTPUT ON 

BEGIN
   EXECUTE IMMEDIATE ('ALTER TABLE GIAC_RECAP_LOSSPD_SUMM_EXT
  ADD (RET_OS_LOSS_CY      NUMBER(16,2),
  RET_OS_EXP_CY       NUMBER(16,2),
  RET_OS_LOSS_PY      NUMBER(16,2),
  RET_OS_EXP_PY       NUMBER(16,2))');

   DBMS_OUTPUT.put_line
                ('Successfully added the following columns to GIAC_RECAP_LOSSPD_SUMM_EXT table: RET_OS_LOSS_CY, RET_OS_EXP_CY, RET_OS_LOSS_PY, RET_OS_LOSS_PY');
EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line ('ERROR: ' || SQLERRM);
END;