CREATE OR REPLACE PACKAGE CPI.EUL4_SBSUMMARY118984 IS

PROCEDURE EXECUTE(NEXT_DATE IN DATE DEFAULT SYSDATE, REFRESH_TYPE IN NUMBER DEFAULT 5, JOB IN NUMBER DEFAULT -1);

END EUL4_SBSUMMARY118984;
/


DROP PACKAGE CPI.EUL4_SBSUMMARY118984;
