CREATE OR REPLACE PACKAGE CPI.flt_risks_pkg AS
    FUNCTION flt_riskformula(p_isscd GIPI_INVOICE.ISS_CD%TYPE, p_prem GIPI_INVOICE.PREM_SEQ_NO%TYPE) RETURN VARCHAR2;
    FUNCTION PREM_RTFormula(p_isscd GIPI_INVOICE.ISS_CD%TYPE, p_prem GIPI_INVOICE.PREM_SEQ_NO%TYPE) RETURN VARCHAR2;
END flt_risks_pkg;
/


