CREATE OR REPLACE PACKAGE CPI.GIACB004_PKG
AS

    PROCEDURE get_ruls_on_incl (p_prod_date            IN       DATE, 
                                p_iss_cd               IN OUT   VARCHAR2, 
                                p_prod_tk_up           IN OUT   NUMBER, 
                                p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                                p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                                p_exclude_special      IN OUT   giac_parameters.param_value_v%TYPE,
                                p_user_id              IN       GIIS_USERS.user_id%type,
                                p_msg                  IN OUT   VARCHAR2);
                                
    PROCEDURE prod_tk_up_1 (p_prod_date            IN       DATE,
                            p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                            p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                            p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                            p_v_neg_incl           IN OUT   VARCHAR2,
                            p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                            p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                            p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                            p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                            p_rule                 IN OUT   VARCHAR2,
                            p_line_cd              IN OUT   VARCHAR2,
                            p_item_no              IN OUT   NUMBER,
                            p_gross_prem           IN OUT   VARCHAR2,
                            p_due_frm_ced          IN OUT   VARCHAR2,
                            p_comm_exp             IN OUT   VARCHAR2,
                            p_v_year               IN OUT   NUMBER,
                            p_v_month              IN OUT   NUMBER,
                            p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                            p_gl_code              IN OUT   VARCHAR2,
                            p_msg                  IN OUT   VARCHAR2);
                            
    PROCEDURE create_gacc_record (p_prod_date     IN       DATE,
                                  p_v_tran_id     IN OUT   giac_acctrans.tran_id%TYPE,
                                  p_v_year        IN OUT   NUMBER,
                                  p_v_month       IN OUT   NUMBER,
                                  p_v_fund_cd     IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                                  p_v_iss_cd      IN OUT   gipi_polbasic.iss_cd%TYPE,
                                  p_v_branch_cd   IN OUT   giac_acctrans.gibr_branch_cd%TYPE);
                                  
    PROCEDURE baeg_delete_acct_entries (p_gen_type    IN   giac_modules.generation_type%TYPE,
                                        p_v_tran_id   IN   giac_acctrans.tran_id%TYPE);
                                        
    FUNCTION get_line_cd (p_line_cd VARCHAR2)
        RETURN NUMBER;
	
    FUNCTION get_subline_cd (p_line_cd VARCHAR2, p_subline_cd VARCHAR2)
       RETURN NUMBER;
       
    PROCEDURE baeg_check_level (cl_level       IN       NUMBER,
                                cl_value       IN       NUMBER,
                                cl_sub_acct1   IN OUT   NUMBER,
                                cl_sub_acct2   IN OUT   NUMBER,
                                cl_sub_acct3   IN OUT   NUMBER,
                                cl_sub_acct4   IN OUT   NUMBER,
                                cl_sub_acct5   IN OUT   NUMBER,
                                cl_sub_acct6   IN OUT   NUMBER,
                                cl_sub_acct7   IN OUT   NUMBER);
                                
    PROCEDURE baeg_check_chart_of_accts (cca_gl_acct_category            giac_acct_entries.gl_acct_category%TYPE,
                                         cca_gl_control_acct             giac_acct_entries.gl_control_acct%TYPE,
                                         cca_gl_sub_acct_1               giac_acct_entries.gl_sub_acct_1%TYPE,
                                         cca_gl_sub_acct_2               giac_acct_entries.gl_sub_acct_2%TYPE,
                                         cca_gl_sub_acct_3               giac_acct_entries.gl_sub_acct_3%TYPE,
                                         cca_gl_sub_acct_4               giac_acct_entries.gl_sub_acct_4%TYPE,
                                         cca_gl_sub_acct_5               giac_acct_entries.gl_sub_acct_5%TYPE,
                                         cca_gl_sub_acct_6               giac_acct_entries.gl_sub_acct_6%TYPE,
                                         cca_gl_sub_acct_7               giac_acct_entries.gl_sub_acct_7%TYPE,
                                         cca_gl_acct_id         IN OUT   giac_chart_of_accts.gl_acct_id%TYPE,
                                         p_gl_code              IN OUT   VARCHAR2,
                                         p_v_tran_id                     giac_acctrans.tran_id%TYPE,
                                         p_msg                           VARCHAR2);
                                         
    PROCEDURE baeg_insert_update_acct_entry (iuae_gl_acct_category   giac_acct_entries.gl_acct_category%TYPE,
                                             iuae_gl_control_acct    giac_acct_entries.gl_control_acct%TYPE,
                                             iuae_gl_sub_acct_1      giac_acct_entries.gl_sub_acct_1%TYPE,
                                             iuae_gl_sub_acct_2      giac_acct_entries.gl_sub_acct_2%TYPE,
                                             iuae_gl_sub_acct_3      giac_acct_entries.gl_sub_acct_3%TYPE,
                                             iuae_gl_sub_acct_4      giac_acct_entries.gl_sub_acct_4%TYPE,
                                             iuae_gl_sub_acct_5      giac_acct_entries.gl_sub_acct_5%TYPE,
                                             iuae_gl_sub_acct_6      giac_acct_entries.gl_sub_acct_6%TYPE,
                                             iuae_gl_sub_acct_7      giac_acct_entries.gl_sub_acct_7%TYPE,
                                             iuae_generation_type    giac_acct_entries.generation_type%TYPE,
                                             iuae_gl_acct_id         giac_chart_of_accts.gl_acct_id%TYPE,
                                             iuae_sl_cd              giac_acct_entries.sl_cd%TYPE,
                                             iuae_debit_amt          giac_acct_entries.debit_amt%TYPE,
                                             iuae_credit_amt         giac_acct_entries.credit_amt%TYPE,
                                             iuae_sl_type_cd         giac_acct_entries.sl_type_cd%TYPE,
                                             p_v_branch_cd          GIAC_ACCTRANS.gibr_branch_cd%type,
                                             p_v_fund_cd            GIAC_ACCTRANS.gfun_fund_cd%type, 
                                             p_v_tran_id            GIAC_ACCTRANS.tran_id%type);
                                             
    PROCEDURE prod_tk_up_2(p_prod_date            IN       DATE,
                           p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                           p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                           p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                           p_v_neg_incl           IN OUT   VARCHAR2,
                           p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                           p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                           p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                           p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                           p_rule                 IN OUT   VARCHAR2,
                           p_line_cd              IN OUT   VARCHAR2,
                           p_item_no              IN OUT   NUMBER,
                           p_gross_prem           IN OUT   VARCHAR2,
                           p_due_frm_ced          IN OUT   VARCHAR2,
                           p_comm_exp             IN OUT   VARCHAR2,
                           p_v_year               IN OUT   NUMBER,
                           p_v_month              IN OUT   NUMBER,
                           p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                           p_gl_code              IN OUT   VARCHAR2,
                           p_msg                  IN OUT   VARCHAR2);
                           
    PROCEDURE prod_tk_up_3(p_prod_date            IN       DATE,
                           p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                           p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                           p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                           p_v_neg_incl           IN OUT   VARCHAR2,
                           p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                           p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                           p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                           p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                           p_rule                 IN OUT   VARCHAR2,
                           p_line_cd              IN OUT   VARCHAR2,
                           p_item_no              IN OUT   NUMBER,
                           p_gross_prem           IN OUT   VARCHAR2,
                           p_due_frm_ced          IN OUT   VARCHAR2,
                           p_comm_exp             IN OUT   VARCHAR2,
                           p_v_year               IN OUT   NUMBER,
                           p_v_month              IN OUT   NUMBER,
                           p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                           p_gl_code              IN OUT   VARCHAR2,
                           p_msg                  IN OUT   VARCHAR2);
                           
    PROCEDURE prod_tk_up_4(p_prod_date            IN       DATE,
                           p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                           p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                           p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                           p_v_neg_incl           IN OUT   VARCHAR2,
                           p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                           p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                           p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                           p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                           p_rule                 IN OUT   VARCHAR2,
                           p_line_cd              IN OUT   VARCHAR2,
                           p_item_no              IN OUT   NUMBER,
                           p_gross_prem           IN OUT   VARCHAR2,
                           p_due_frm_ced          IN OUT   VARCHAR2,
                           p_comm_exp             IN OUT   VARCHAR2,
                           p_v_year               IN OUT   NUMBER,
                           p_v_month              IN OUT   NUMBER,
                           p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                           p_gl_code              IN OUT   VARCHAR2,
                           p_msg                  IN OUT   VARCHAR2);
                           
    PROCEDURE prod_tk_up_5(p_prod_date            IN       DATE,
                           p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                           p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                           p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                           p_v_neg_incl           IN OUT   VARCHAR2,
                           p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                           p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                           p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                           p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                           p_rule                 IN OUT   VARCHAR2,
                           p_line_cd              IN OUT   VARCHAR2,
                           p_item_no              IN OUT   NUMBER,
                           p_gross_prem           IN OUT   VARCHAR2,
                           p_due_frm_ced          IN OUT   VARCHAR2,
                           p_comm_exp             IN OUT   VARCHAR2,
                           p_v_year               IN OUT   NUMBER,
                           p_v_month              IN OUT   NUMBER,
                           p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                           p_gl_code              IN OUT   VARCHAR2,
                           p_msg                  IN OUT   VARCHAR2,
                           p_acct_line_cd         IN OUT   giis_line.acct_line_cd%type,
                           p_gl_acct_id           IN OUT   giac_chart_of_accts.gl_acct_id%type);
                               
    PROCEDURE prod_tk_up_1_reg(p_prod_date            IN       DATE,
                               p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                               p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                               p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                               p_v_neg_incl           IN OUT   VARCHAR2,
                               p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                               p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                               p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                               p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                               p_rule                 IN OUT   VARCHAR2,
                               p_line_cd              IN OUT   VARCHAR2,
                               p_item_no              IN OUT   NUMBER,
                               p_gross_prem           IN OUT   VARCHAR2,
                               p_due_frm_ced          IN OUT   VARCHAR2,
                               p_comm_exp             IN OUT   VARCHAR2,
                               p_v_year               IN OUT   NUMBER,
                               p_v_month              IN OUT   NUMBER,
                               p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                               p_gl_code              IN OUT   VARCHAR2,
                               p_msg                  IN OUT   VARCHAR2);
                               
    PROCEDURE prod_tk_up_2_reg(p_prod_date            IN       DATE,
                               p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                               p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                               p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                               p_v_neg_incl           IN OUT   VARCHAR2,
                               p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                               p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                               p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                               p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                               p_rule                 IN OUT   VARCHAR2,
                               p_line_cd              IN OUT   VARCHAR2,
                               p_item_no              IN OUT   NUMBER,
                               p_gross_prem           IN OUT   VARCHAR2,
                               p_due_frm_ced          IN OUT   VARCHAR2,
                               p_comm_exp             IN OUT   VARCHAR2,
                               p_v_year               IN OUT   NUMBER,
                               p_v_month              IN OUT   NUMBER,
                               p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                               p_gl_code              IN OUT   VARCHAR2,
                               p_msg                  IN OUT   VARCHAR2);
                               
    PROCEDURE prod_tk_up_3_reg(p_prod_date            IN       DATE,
                               p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                               p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                               p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                               p_v_neg_incl           IN OUT   VARCHAR2,
                               p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                               p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                               p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                               p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                               p_rule                 IN OUT   VARCHAR2,
                               p_line_cd              IN OUT   VARCHAR2,
                               p_item_no              IN OUT   NUMBER,
                               p_gross_prem           IN OUT   VARCHAR2,
                               p_due_frm_ced          IN OUT   VARCHAR2,
                               p_comm_exp             IN OUT   VARCHAR2,
                               p_v_year               IN OUT   NUMBER,
                               p_v_month              IN OUT   NUMBER,
                               p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                               p_gl_code              IN OUT   VARCHAR2,
                               p_msg                  IN OUT   VARCHAR2);
                               
    PROCEDURE prod_tk_up_4_reg(p_prod_date            IN       DATE,
                               p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                               p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                               p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                               p_v_neg_incl           IN OUT   VARCHAR2,
                               p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                               p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                               p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                               p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                               p_rule                 IN OUT   VARCHAR2,
                               p_line_cd              IN OUT   VARCHAR2,
                               p_item_no              IN OUT   NUMBER,
                               p_gross_prem           IN OUT   VARCHAR2,
                               p_due_frm_ced          IN OUT   VARCHAR2,
                               p_comm_exp             IN OUT   VARCHAR2,
                               p_v_year               IN OUT   NUMBER,
                               p_v_month              IN OUT   NUMBER,
                               p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                               p_gl_code              IN OUT   VARCHAR2,
                               p_msg                  IN OUT   VARCHAR2);
                               
    PROCEDURE prod_tk_up_5_reg(p_prod_date            IN       DATE,
                               p_outputvat_item_no    IN OUT   giac_module_entries.item_no%TYPE,
                               p_inputvat_item_no     IN OUT   giac_module_entries.item_no%TYPE,
                               p_v_iss_cd             IN OUT   gipi_polbasic.iss_cd%TYPE,
                               p_v_neg_incl           IN OUT   VARCHAR2,
                               p_v_branch_cd          IN OUT   giac_acctrans.gibr_branch_cd%TYPE,
                               p_v_fund_cd            IN OUT   giac_acctrans.gfun_fund_cd%TYPE,
                               p_v_tran_id            IN OUT   giac_acctrans.tran_id%TYPE,
                               p_prem_rec_gross_tag   IN OUT   giac_parameters.param_value_v%TYPE,
                               p_rule                 IN OUT   VARCHAR2,
                               p_line_cd              IN OUT   VARCHAR2,
                               p_item_no              IN OUT   NUMBER,
                               p_gross_prem           IN OUT   VARCHAR2,
                               p_due_frm_ced          IN OUT   VARCHAR2,
                               p_comm_exp             IN OUT   VARCHAR2,
                               p_v_year               IN OUT   NUMBER,
                               p_v_month              IN OUT   NUMBER,
                               p_gen_type             IN OUT   GIAC_MODULES.generation_type%type,
                               p_gl_code              IN OUT   VARCHAR2,
                               p_msg                  IN OUT   VARCHAR2,
                               p_acct_line_cd         IN OUT   giis_line.acct_line_cd%type,
                               p_gl_acct_id           IN OUT   giac_chart_of_accts.gl_acct_id%type);
                               
    PROCEDURE check_debit_credit_amounts(p_prod_date				IN DATE,
                                         p_module_item_no_Inc_adj   IN GIAC_MODULE_ENTRIES.item_no%type,
                                         p_module_item_no_Exp_adj   IN GIAC_MODULE_ENTRIES.item_no%type,
                                         p_module_name			    IN GIAC_MODULES.module_name%type,
                                         p_fund_Cd				    IN GIAC_ACCT_ENTRIES.gacc_gfun_fund_cd%type,
                                         p_balance					IN OUT NUMBER,
                                         p_msg						IN OUT VARCHAR2);
                                         
    PROCEDURE adjust (v_tran_id          			  giac_acctrans.tran_id%TYPE,
                      v_module_item_no   			  giac_module_entries.item_no%TYPE,
                      v_branch_cd        		      giac_acctrans.gibr_branch_cd%TYPE,
                      p_module_item_no_exp_adj   IN   giac_module_entries.item_no%TYPE,
                      p_module_name              IN   giac_modules.module_name%TYPE,
                      p_fund_cd                  IN   giac_acct_entries.gacc_gfun_fund_cd%TYPE,
                      p_module_item_no_inc_adj   IN   giac_module_entries.item_no%TYPE,
                      p_balance                  IN   NUMBER);
END;
/


