CREATE OR REPLACE PACKAGE CPI.GIACR602_PKG
AS
   /*
   **  Created by   : Dren Niebres
   **  Date Created : 04.27.2015
   **  Reference By : (GIACR602-  LIST OF UPLOADED FILES)
   **  Description  : POPULATE LIST OF UPLOADED FILES REPORT
   */
   TYPE POPULATE_GIACR602_TYPE IS RECORD (
        COMPANY_NAME        GIIS_PARAMETERS.PARAM_VALUE_V%TYPE,
        COMPANY_ADDRESS     GIIS_PARAMETERS.PARAM_VALUE_V%TYPE,  
        REPORT_TITLE        GIIS_REPORTS.REPORT_TITLE%TYPE,
        SOURCE_1            GIAC_FILE_SOURCE.SOURCE_NAME%TYPE,
        TRANSACTION_1       CG_REF_CODES.RV_MEANING%TYPE,
        INTERMEDIARY        VARCHAR2 (400),
        CEDING_COMPANY      GIIS_REINSURER.RI_NAME%TYPE,
        FILE_NAME           GIAC_UPLOAD_FILE.FILE_NAME%TYPE,
        DEPOSIT_DATE        GIAC_UPLOAD_FILE.PAYMENT_DATE%TYPE,    
        CONVERT_DATE        GIAC_UPLOAD_FILE.CONVERT_DATE%TYPE,
        UPLOAD_DATE         GIAC_UPLOAD_FILE.UPLOAD_DATE%TYPE,
        FILE_STATUS         CG_REF_CODES.RV_MEANING%TYPE,
        SOURCE_CD           GIAC_UPLOAD_FILE.SOURCE_CD%TYPE,
        TRANSACTION_TYPE    GIAC_UPLOAD_FILE.TRANSACTION_TYPE%TYPE,
        FILE_NO             GIAC_UPLOAD_FILE.FILE_NO%TYPE,
        ATM_TAG             GIAC_FILE_SOURCE.ATM_TAG%TYPE,
        RI_CD               GIAC_UPLOAD_FILE.RI_CD%TYPE,
        TRAN_CLASS          GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        TRAN_ID             GIAC_UPLOAD_FILE.TRAN_ID%TYPE,
        INTM_NO             GIAC_UPLOAD_FILE.INTM_NO%TYPE,
        REPORT_DATE         VARCHAR2 (400)
   );
   TYPE POPULATE_GIACR602_TAB IS TABLE OF POPULATE_GIACR602_TYPE;
-------------------------------------------------------------------------------   
   TYPE POPULATE_GIACR602_TRAN1_A_TYPE IS RECORD (
        PAYOR               GIAC_UPLOAD_PREM.PAYOR%TYPE,
        POLICY_NO           VARCHAR2 (200),
        TRAN_CLASS          GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        REF_NO              VARCHAR2 (100),
        PARTICULARS         VARCHAR2 (2100),
        COLLECTION_AMT      GIAC_UPLOAD_PREM.COLLECTION_AMT%TYPE
   );
   TYPE POPULATE_GIACR602_TRAN1_A_TAB IS TABLE OF POPULATE_GIACR602_TRAN1_A_TYPE; 
-------------------------------------------------------------------------------   
   TYPE POPULATE_GIACR602_TRAN1_B_TYPE IS RECORD (
        PAYOR               GIAC_UPLOAD_PREM_ATM.PAYOR%TYPE,
        ATM_NUMBER          GIAC_UPLOAD_PREM_ATM.BILL_NO%TYPE,
        TRAN_CLASS          GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        REF_NO              VARCHAR2 (100),
        PARTICULARS         VARCHAR2 (2100),        
        COLLECTION_AMT      GIAC_UPLOAD_PREM_ATM.COLLECTION_AMT%TYPE        
   );
   TYPE POPULATE_GIACR602_TRAN1_B_TAB IS TABLE OF POPULATE_GIACR602_TRAN1_B_TYPE; 
-------------------------------------------------------------------------------   
   TYPE POPULATE_GIACR602_TRAN2_TYPE IS RECORD (
        PAYOR               GIAC_UPLOAD_PREM_COMM.PAYOR%TYPE,
        POLICY_NO           VARCHAR2 (100), 
        TRAN_CLASS          GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        REF_NO              VARCHAR2 (100),
        PARTICULARS         VARCHAR2 (2100),           
        GROSS_PREMIUM       GIAC_UPLOAD_PREM_COMM.GROSS_PREM_AMT%TYPE,
        COMMISSION          GIAC_UPLOAD_PREM_COMM.COMM_AMT%TYPE,
        WITHHOLDING_TAX     GIAC_UPLOAD_PREM_COMM.WHTAX_AMT%TYPE,
        INPUT_VAT           GIAC_UPLOAD_PREM_COMM.INPUT_VAT_AMT%TYPE,
        NET_AMT_DUE         GIAC_UPLOAD_PREM_COMM.NET_AMT_DUE%TYPE
   );
   TYPE POPULATE_GIACR602_TRAN2_TAB IS TABLE OF POPULATE_GIACR602_TRAN2_TYPE;
-------------------------------------------------------------------------------   
   TYPE POPULATE_GIACR602_TRAN3_TYPE IS RECORD (
        ASSURED             GIAC_UPLOAD_INWFACUL_PREM.ASSURED%TYPE,
        POLICY_NO           VARCHAR2 (100), 
        TRAN_CLASS          GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        REF_NO              VARCHAR2 (100),
        PARTICULARS         VARCHAR2 (2100),         
        PREMIUM             GIAC_UPLOAD_INWFACUL_PREM.FPREM_AMT%TYPE,
        VAT_ON_PREM         GIAC_UPLOAD_INWFACUL_PREM.FTAX_AMT%TYPE,
        RI_COMMISSION       GIAC_UPLOAD_INWFACUL_PREM.FCOMM_AMT%TYPE,
        VAT_ON_COMM         GIAC_UPLOAD_INWFACUL_PREM.FCOMM_VAT%TYPE,
        NET_DUE             GIAC_UPLOAD_INWFACUL_PREM.FCOLLECTION_AMT%TYPE,
        CURRENCY            GIIS_CURRENCY.CURRENCY_DESC%TYPE,       
        CONVERT_RATE        GIAC_UPLOAD_INWFACUL_PREM.CONVERT_RATE%TYPE             
   );
   TYPE POPULATE_GIACR602_TRAN3_TAB IS TABLE OF POPULATE_GIACR602_TRAN3_TYPE;   
-------------------------------------------------------------------------------   
   TYPE POPULATE_GIACR602_TRAN4_TYPE IS RECORD (
        CURRENCY            GIIS_CURRENCY.CURRENCY_DESC%TYPE,  
        CONVERT_RATE        GIAC_UPLOAD_OUTFACUL_PREM.CONVERT_RATE%TYPE,
        BINDER_NO           VARCHAR2 (100), 
        TRAN_CLASS          GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        REF_NO              VARCHAR2 (100),
        PARTICULARS         VARCHAR2 (2100),            
        PREMIUM             GIAC_UPLOAD_OUTFACUL_PREM.FPREM_AMT%TYPE,
        VAT_ON_PREM         GIAC_UPLOAD_OUTFACUL_PREM.FPREM_VAT%TYPE,
        RI_COMMISSION       GIAC_UPLOAD_OUTFACUL_PREM.FCOMM_AMT%TYPE,
        VAT_ON_COMM         GIAC_UPLOAD_OUTFACUL_PREM.FCOMM_VAT%TYPE,
        WITHHOLDING_VAT     GIAC_UPLOAD_OUTFACUL_PREM.FWHOLDING_VAT%TYPE,
        NET_DUE             GIAC_UPLOAD_OUTFACUL_PREM.FDISB_AMT%TYPE
   );
   TYPE POPULATE_GIACR602_TRAN4_TAB IS TABLE OF POPULATE_GIACR602_TRAN4_TYPE;  
-------------------------------------------------------------------------------   
   TYPE POPULATE_GIACR602_TRAN5_TYPE IS RECORD (
        PAYOR               GIAC_UPLOAD_PREM_REFNO.PAYOR%TYPE,
        BANK_REF_NO         GIAC_UPLOAD_PREM_REFNO.BANK_REF_NO%TYPE,
        UPLOAD_DATE         GIAC_UPLOAD_PREM_REFNO.UPLOAD_DATE%TYPE,
        TRAN_CLASS          GIAC_ACCTRANS.TRAN_CLASS%TYPE,
        REF_NO              VARCHAR2 (50),
        PARTICULARS         GIAC_ORDER_OF_PAYTS.PARTICULARS%TYPE,
        COLLECTION_AMT      GIAC_UPLOAD_PREM_REFNO.COLLECTION_AMT%TYPE  
   );
   TYPE POPULATE_GIACR602_TRAN5_TAB IS TABLE OF POPULATE_GIACR602_TRAN5_TYPE;                
   FUNCTION POPULATE_GIACR602 (
        P_SOURCE_CD         GIAC_UPLOAD_FILE.SOURCE_CD%TYPE,
        P_FILE_NAME         GIAC_UPLOAD_FILE.FILE_NAME%TYPE,
        P_TRAN_TYPE         GIAC_UPLOAD_FILE.TRANSACTION_TYPE%TYPE,
        P_FROM_DATE         GIAC_UPLOAD_FILE.CONVERT_DATE%TYPE,
        P_TO_DATE           GIAC_UPLOAD_FILE.CONVERT_DATE%TYPE
   )
        RETURN POPULATE_GIACR602_TAB PIPELINED;
   FUNCTION POPULATE_GIACR602_TRAN1_A (
        P_SOURCE_CD         GIAC_UPLOAD_PREM.SOURCE_CD%TYPE,
        P_FILE_NO           GIAC_UPLOAD_PREM.FILE_NO%TYPE,
        P_TRAN_CLASS        GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        P_TRAN_ID           GIAC_UPLOAD_FILE.TRAN_ID%TYPE    
   )
        RETURN POPULATE_GIACR602_TRAN1_A_TAB PIPELINED;
   FUNCTION POPULATE_GIACR602_TRAN1_B (
        P_SOURCE_CD         GIAC_UPLOAD_PREM_ATM.SOURCE_CD%TYPE,
        P_FILE_NO           GIAC_UPLOAD_PREM_ATM.FILE_NO%TYPE,
        P_TRAN_CLASS        GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        P_TRAN_ID           GIAC_UPLOAD_PREM_ATM.TRAN_ID%TYPE     
   )
        RETURN POPULATE_GIACR602_TRAN1_B_TAB PIPELINED;    
   FUNCTION POPULATE_GIACR602_TRAN2 (
        P_SOURCE_CD         GIAC_UPLOAD_PREM_COMM.SOURCE_CD%TYPE,
        P_FILE_NO           GIAC_UPLOAD_PREM_COMM.FILE_NO%TYPE,
        P_TRAN_CLASS        GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        P_TRAN_ID           GIAC_UPLOAD_PREM_COMM.TRAN_ID%TYPE 
   )
        RETURN POPULATE_GIACR602_TRAN2_TAB PIPELINED;
   FUNCTION POPULATE_GIACR602_TRAN3 (
        P_SOURCE_CD         GIAC_UPLOAD_INWFACUL_PREM.SOURCE_CD%TYPE,
        P_FILE_NO           GIAC_UPLOAD_INWFACUL_PREM.FILE_NO%TYPE,  
        P_TRAN_CLASS        GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        P_TRAN_ID           GIAC_UPLOAD_INWFACUL_PREM.TRAN_ID%TYPE         
   )
        RETURN POPULATE_GIACR602_TRAN3_TAB PIPELINED;        
   FUNCTION POPULATE_GIACR602_TRAN4 (
        P_SOURCE_CD         GIAC_UPLOAD_OUTFACUL_PREM.SOURCE_CD%TYPE,
        P_FILE_NO           GIAC_UPLOAD_OUTFACUL_PREM.FILE_NO%TYPE,
        P_TRAN_CLASS        GIAC_UPLOAD_FILE.TRAN_CLASS%TYPE,
        P_TRAN_ID           GIAC_UPLOAD_OUTFACUL_PREM.TRAN_ID%TYPE               
   )
        RETURN POPULATE_GIACR602_TRAN4_TAB PIPELINED;  
   FUNCTION POPULATE_GIACR602_TRAN5 (
        P_SOURCE_CD         GIAC_UPLOAD_FILE.SOURCE_CD%TYPE,
        P_FILE_NO           GIAC_UPLOAD_FILE.FILE_NO%TYPE,
        P_FROM_DATE         GIAC_UPLOAD_FILE.CONVERT_DATE%TYPE,
        P_TO_DATE           GIAC_UPLOAD_FILE.CONVERT_DATE%TYPE             
   )
        RETURN POPULATE_GIACR602_TRAN5_TAB PIPELINED;                          

END GIACR602_PKG;
/