CREATE OR REPLACE PACKAGE CPI.gipir947_pkg
AS
   TYPE gipir947_record_type IS RECORD (
      tarf_cd                  gipi_risk_profile.tarf_cd%TYPE,
      tarf_line                gipi_risk_profile.line_cd%TYPE,
      line_cd                  gipi_risk_profile.line_cd%TYPE,
      range_from               NUMBER,
      range_to                 NUMBER,
      policy_count             gipi_risk_profile.policy_count%TYPE,
      net_retention            gipi_risk_profile.net_retention%TYPE,
      net_retention_tsi        gipi_risk_profile.net_retention_tsi%TYPE,
      sec_net_retention_tsi    gipi_risk_profile.sec_net_retention_tsi%TYPE,
      sec_net_retention_prem   gipi_risk_profile.sec_net_retention_prem%TYPE,
      quota_share              gipi_risk_profile.quota_share%TYPE,
      quota_share_tsi          gipi_risk_profile.quota_share_tsi%TYPE,
      facultative              gipi_risk_profile.facultative%TYPE,
      facultative_tsi          gipi_risk_profile.facultative_tsi%TYPE,
      treaty_prem              NUMBER,
      treaty2_prem             NUMBER,
      treaty3_prem             NUMBER,
      treaty4_prem             NUMBER,
      treaty5_prem             NUMBER,
      treaty6_prem             NUMBER,
      treaty7_prem             NUMBER,
      treaty8_prem             NUMBER,
      treaty9_prem             NUMBER,
      treaty10_prem            NUMBER,
      treaty_tsi               NUMBER,
      treaty2_tsi              NUMBER,
      treaty3_tsi              NUMBER,
      treaty4_tsi              NUMBER,
      treaty5_tsi              NUMBER,
      treaty6_tsi              NUMBER,
      treaty7_tsi              NUMBER,
      treaty8_tsi              NUMBER,
      treaty9_tsi              NUMBER,
      treaty10_tsi             NUMBER,
      net_retention_cnt        gipi_risk_profile.net_retention_cnt%TYPE,
      facultative_cnt          gipi_risk_profile.facultative_cnt%TYPE,
      treaty_cnt               gipi_risk_profile.treaty_cnt%TYPE,
      treaty2_cnt              NUMBER,
      treaty3_cnt              NUMBER,
      treaty4_cnt              NUMBER,
      treaty5_cnt              NUMBER,
      treaty6_cnt              NUMBER,
      treaty7_cnt              NUMBER,
      treaty8_cnt              NUMBER,
      treaty9_cnt              NUMBER,
      treaty10_cnt             NUMBER,
      trty_name                gipi_risk_profile.trty_name%TYPE,
      trty2_name               VARCHAR2 (50),
      trty3_name               VARCHAR2 (50),
      trty4_name               VARCHAR2 (50),
      trty5_name               VARCHAR2 (50),
      trty6_name               VARCHAR2 (50),
      trty7_name               VARCHAR2 (50),
      trty8_name               VARCHAR2 (50),
      trty9_name               VARCHAR2 (50),
      trty10_name              VARCHAR2 (50),
      cf_sec_netret_amt        NUMBER,
      trty_amt                 NUMBER,
      trty2_amt                NUMBER,
      trty3_amt                NUMBER,
      trty4_amt                NUMBER,
      trty5_amt                NUMBER,
      trty6_amt                NUMBER,
      trty7_amt                NUMBER,
      total_tsi                NUMBER,
      total_prem                NUMBER,
      line_name                VARCHAR2 (100),
      tarf_desc                VARCHAR2 (100),
      cf_from                  VARCHAR2 (100),
      cf_to                    VARCHAR2 (100),
      company_name             VARCHAR2 (100),
      company_address          VARCHAR2 (100),
      title                    VARCHAR2 (200),
      mjm                      VARCHAR2 (1)
   );

   TYPE gipir947_record_tab IS TABLE OF gipir947_record_type;

   FUNCTION get_gipir947_record (
      p_line_cd         VARCHAR2,
      p_starting_date   VARCHAR2,
      p_ending_date     VARCHAR2,
      p_by_tarf         VARCHAR2,
      p_param_date      VARCHAR2,
      p_user_id         VARCHAR2
   )
      RETURN gipir947_record_tab PIPELINED;
END;
/


