CREATE OR REPLACE PACKAGE CPI.GIPI_WGRP_ITMS_BENEFICIARY_PKG
AS
	Procedure del_GIPI_WGRP_ITMS_BENEFICIARY (p_par_id IN GIPI_WGRP_ITEMS_BENEFICIARY.par_id%TYPE);
END GIPI_WGRP_ITMS_BENEFICIARY_PKG;
/


