CREATE OR REPLACE PACKAGE CPI.gipis039_ref_cursor_pkg
AS
   TYPE endt_fi_item_type IS RECORD (
      ann_tsi_amt            gipi_witem.ann_tsi_amt%TYPE,
      ann_prem_amt           gipi_witem.ann_prem_amt%TYPE,
      rec_flag               gipi_witem.rec_flag%TYPE,
      item_no                gipi_witem.item_no%TYPE,
      item_title             gipi_witem.item_title%TYPE,
      currency_cd            gipi_witem.currency_cd%TYPE,
      currency_desc          giis_currency.currency_desc%TYPE,
      currency_rt            gipi_witem.currency_rt%TYPE,
      coverage_cd            gipi_witem.coverage_cd%TYPE,
      coverage_desc          giis_coverage.coverage_desc%TYPE,
      group_cd               gipi_witem.group_cd%TYPE,
      group_desc             giis_group.group_desc%TYPE,
      risk_no                gipi_witem.risk_no%TYPE,
      risk_item_no           gipi_witem.risk_item_no%TYPE,
      block_no               gipi_wfireitm.block_no%TYPE,
      district_no            gipi_wfireitm.district_no%TYPE,
      block_id               gipi_wfireitm.block_id%TYPE,
      risk_cd                gipi_wfireitm.risk_cd%TYPE,
      risk_desc              giis_risks.risk_desc%TYPE,
      province_cd            giis_province.province_cd%TYPE,
      province_desc          giis_province.province_desc%TYPE,
      city_cd                giis_block.city_cd%TYPE,
      city                   giis_block.city%TYPE,
      eq_zone                giis_eqzone.eq_zone%TYPE,
      eq_desc                giis_eqzone.eq_desc%TYPE,
      flood_zone             giis_flood_zone.flood_zone%TYPE,
      flood_zone_desc        giis_flood_zone.flood_zone_desc%TYPE,
      typhoon_zone           giis_typhoon_zone.typhoon_zone%TYPE,
      typhoon_zone_desc      giis_typhoon_zone.typhoon_zone_desc%TYPE,
      tariff_zone            giis_tariff_zone.tariff_zone%TYPE,
      tariff_zone_desc       giis_tariff_zone.tariff_zone_desc%TYPE,
      tarf_cd                gipi_wfireitm.tarf_cd%TYPE,
      region_cd              gipi_witem.region_cd%TYPE,
      region_desc            giis_region.region_desc%TYPE,
      item_desc              gipi_witem.item_desc%TYPE,
      other_info             gipi_witem.other_info%TYPE,
      from_date              gipi_witem.from_date%TYPE,
      TO_DATE                gipi_witem.TO_DATE%TYPE,
      assignee               gipi_wfireitm.assignee%TYPE,
      fr_item_type           giis_fi_item_type.fr_itm_tp_ds%TYPE,
      fr_itm_tp_ds           giis_fi_item_type.fr_itm_tp_ds%TYPE,
      construction_cd        giis_fire_construction.construction_cd%TYPE,
      construction_desc      giis_fire_construction.construction_desc%TYPE,
      construction_remarks   gipi_fireitem.construction_remarks%TYPE,
      loc_risk1              gipi_wfireitm.loc_risk1%TYPE,
      loc_risk2              gipi_wfireitm.loc_risk2%TYPE,
      loc_risk3              gipi_wfireitm.loc_risk3%TYPE,
      front                  gipi_wfireitm.front%TYPE,
      rear                   gipi_wfireitm.rear%TYPE,
      LEFT                   gipi_wfireitm.LEFT%TYPE,
      RIGHT                  gipi_wfireitm.RIGHT%TYPE,
      occupancy_cd           giis_fire_occupancy.occupancy_cd%TYPE,
      occupancy_desc         giis_fire_occupancy.occupancy_desc%TYPE,
      occupancy_remarks      gipi_wfireitm.occupancy_remarks%TYPE
   );

   TYPE rc_endt_fi_item IS REF CURSOR
      RETURN endt_fi_item_type;

   TYPE endt_mc_item_type IS RECORD (
      item_no               gipi_witem.item_no%TYPE,
      item_title            gipi_witem.item_title%TYPE,
      ann_tsi_amt           gipi_witem.ann_tsi_amt%TYPE,
      ann_prem_amt          gipi_witem.ann_prem_amt%TYPE,
      rec_flag              gipi_witem.rec_flag%TYPE,
      currency_rt           gipi_witem.currency_rt%TYPE,
      coverage_cd           gipi_witem.coverage_cd%TYPE,
      coverage_desc         giis_coverage.coverage_desc%TYPE,
      group_cd              gipi_witem.group_cd%TYPE,
      group_desc            giis_group.group_desc%TYPE,
      currency_cd           gipi_witem.currency_cd%TYPE,
      currency_desc         giis_currency.currency_desc%TYPE,
      short_name            giis_currency.short_name%TYPE,
      region_cd             gipi_witem.region_cd%TYPE,
      region_desc           giis_region.region_desc%TYPE,
      subline_cd            gipi_wvehicle.subline_cd%TYPE,
      motor_coverage        gipi_wvehicle.motor_coverage%TYPE,
      motor_coverage_desc   cg_ref_codes.rv_meaning%TYPE,
      assignee              gipi_wvehicle.assignee%TYPE,
      origin                gipi_wvehicle.origin%TYPE,
      plate_no              gipi_wvehicle.plate_no%TYPE,
      mv_file_no            gipi_wvehicle.mv_file_no%TYPE,
      basic_color_cd        gipi_wvehicle.basic_color_cd%TYPE,
      mot_type              gipi_wvehicle.mot_type%TYPE,
      motor_type_desc       giis_motortype.motor_type_desc%TYPE,
      serial_no             gipi_wvehicle.serial_no%TYPE,
      coc_type              gipi_wvehicle.coc_type%TYPE,
      coc_yy                gipi_wvehicle.coc_yy%TYPE,
      --coc_serial_no         gipi_wvehicle.coc_serial_no%TYPE,
      acquired_from         gipi_wvehicle.acquired_from%TYPE,
      destination           gipi_wvehicle.destination%TYPE,
      model_year            gipi_wvehicle.model_year%TYPE,
      no_of_pass            gipi_wvehicle.no_of_pass%TYPE,
      color_cd              gipi_wvehicle.color_cd%TYPE,
      color                 gipi_wvehicle.color%TYPE,
      unladen_wt            gipi_wvehicle.unladen_wt%TYPE,
      subline_type_cd       giis_mc_subline_type.subline_type_cd%TYPE,
      subline_type_desc     giis_mc_subline_type.subline_type_desc%TYPE,
      motor_no              gipi_wvehicle.motor_no%TYPE,
      type_of_body_cd       gipi_wvehicle.type_of_body_cd%TYPE,
      car_company_cd        gipi_wvehicle.car_company_cd%TYPE,
      car_company           giis_mc_car_company.car_company%TYPE,
      make                  gipi_wvehicle.make%TYPE,
      make_cd               gipi_wvehicle.make_cd%TYPE,
      series_cd             gipi_wvehicle.series_cd%TYPE,
      towing                gipi_wvehicle.towing%TYPE,
      repair_lim            gipi_wvehicle.repair_lim%TYPE
   );

   TYPE rc_endt_mc_item IS REF CURSOR
      RETURN endt_mc_item_type;
END gipis039_ref_cursor_pkg;
/


