DROP FUNCTION CPI.ROW_COUNT_ADZ;

CREATE OR REPLACE FUNCTION CPI.Row_Count_Adz(tab_name VARCHAR2)
RETURN NUMBER IS
row_count NUMBER;
begin
EXECUTE IMMEDIATE ('SELECT COUNT(*) INTO ROW_COUNT FROM '||Tab_name||';');
RETURN(row_count);
END;
/


