SET serveroutput ON;
DECLARE
    v_exists    NUMBER := 0;
BEGIN
    SELECT DISTINCT 1
      INTO v_exists
      FROM all_constraints
     WHERE owner = 'CPI'
       AND constraint_name = 'COINTRMDRY_INTRMDRY_FK';
       
    IF v_exists = 1 THEN
        EXECUTE IMMEDIATE ('ALTER TABLE CPI.GIIS_INTERMEDIARY DROP CONSTRAINT COINTRMDRY_INTRMDRY_FK');
        DBMS_OUTPUT.PUT_LINE('Successfully dropped constraint COINTRMDRY_INTRMDRY_FK of GIIS_INTERMEDIARY.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    	DBMS_OUTPUT.PUT_LINE('Constraint COINTRMDRY_INTRMDRY_FK of GIIS_INTERMEDIARY already dropped.');
    WHEN OTHERS THEN
        EXECUTE IMMEDIATE ('ALTER TABLE CPI.GIIS_INTERMEDIARY DROP CONSTRAINT COINTRMDRY_INTRMDRY_FK');
        DBMS_OUTPUT.PUT_LINE('Successfully dropped constraint COINTRMDRY_INTRMDRY_FK of GIIS_INTERMEDIARY.');
END;