SET SERVEROUTPUT ON 
BEGIN 
    
    EXECUTE IMMEDIATE 'CREATE BITMAP INDEX  GIAC_SOA_REP_EXT_USER_ID_IDX ON   GIAC_SOA_REP_EXT  (USER_ID)';
   
 DBMS_OUTPUT.PUT_LINE('index created');
EXCEPTION 
WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE(SQLERRM || '-' || SQLCODE);
END;
 /