SET SERVEROUTPUT ON

BEGIN
   EXECUTE IMMEDIATE
      ('ALTER TABLE CPI.GIAC_CM_DM ADD RI_COMM_VAT NUMBER(12, 2)');

   DBMS_OUTPUT.PUT_LINE (
      'Successfully added RI_COMM_VAT column to GIAC_CM_DM table.');
EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line ('ERROR: ' || SQLERRM);
END;