DROP PROCEDURE CPI.B520_POST_QUERY_GIPIS010;

CREATE OR REPLACE PROCEDURE CPI.B520_Post_Query_Gipis010(B520_ACCESSORY_CD NUMBER,
                     B520_ACCESSORY OUT VARCHAR2)
IS
BEGIN
   FOR C IN(SELECT ACCESSORY_DESC 
           FROM GIIS_ACCESSORY 
          WHERE ACCESSORY_CD = B520_ACCESSORY_CD) LOOP
 B520_ACCESSORY:=C.ACCESSORY_DESC;
END LOOP;
END;
/


