DROP PROCEDURE CPI.CGFK$CHK_B540SUBLWPOL_GIPIS002;

CREATE OR REPLACE PROCEDURE CPI.Cgfk$chk_B540sublwpol_Gipis002
  (P_FIELD_LEVEL IN BOOLEAN,  /* Is the trigger item level? */
   B540_LINE_CD IN VARCHAR2,
   B540_SUBLINE_CD IN VARCHAR2,
   B240_LINE_CD IN VARCHAR2,
   B540_DSP_SUBLINE_NAME IN OUT VARCHAR2,
   v_others IN OUT NUMBER) IS
/* Validate foreign key value/query lookup data. */
BEGIN
  DECLARE
    CURSOR C IS
      SELECT A210.SUBLINE_NAME
      FROM   GIIS_SUBLINE A210
      WHERE  A210.LINE_CD = B540_LINE_CD
      AND    A210.SUBLINE_CD = B540_SUBLINE_CD
      AND     line_cd = B240_LINE_CD;
  BEGIN
    OPEN C;
    FETCH C
    INTO   B540_DSP_SUBLINE_NAME;
    IF C%NOTFOUND THEN
      RAISE NO_DATA_FOUND;
    END IF;
    CLOSE C;
  EXCEPTION
    WHEN OTHERS THEN
      v_others := SQLCODE;
      --CGTE$OTHER_EXCEPTIONS;
  END;
END;
/


