CREATE OR REPLACE PROCEDURE CPI.EUL4_PSUMMARY119053(REFRESH_TYPE IN NUMBER DEFAULT 5, JOB IN NUMBER DEFAULT -1) IS
  TEMPL_SDO_ID            NUMBER := 119053;
  TEMPL_REFRESH_TYPE      NUMBER := REFRESH_TYPE;
  MATVIEW_OWNER           VARCHAR2(2000) := 'CPI';
  MATVIEW_OWNER_SQL_IDENT VARCHAR2(2000) := 'CPI';
  MATVIEW_NAME            VARCHAR2(2000) := 'EUL4_MV119049';
  MATVIEW_NAME_SQL_IDENT  VARCHAR2(2000) := 'EUL4_MV119049';
  REFRESH_TYPE_CHAR       CHAR(1);
  ERR_NUM                 NUMBER;
  ERR_MESSAGE             VARCHAR2(200);
BEGIN
  EUL4_CSUMMARY118979.INCREMENT_SUMMARY_SET_COUNT(118979);
  IF ((EUL4_CSUMMARY118979.IS_REFRESH_ON_COMMIT(MATVIEW_OWNER, MATVIEW_NAME)) AND
     (JOB <> -1) AND
     (EUL4_CSUMMARY118979.IS_MV_EMPTY(MATVIEW_OWNER_SQL_IDENT, MATVIEW_NAME_SQL_IDENT) = FALSE)) THEN
    RETURN;
  END IF;
  EUL4_CSUMMARY118979.TRANSLATE_REFRESH_TYPE(TEMPL_REFRESH_TYPE);
  IF (TEMPL_REFRESH_TYPE = 5) THEN
    TEMPL_REFRESH_TYPE := EUL4_CSUMMARY118979.GET_CALCULATED_REFRESH_TYPE(MATVIEW_OWNER,
                                                                   MATVIEW_NAME);
  END IF;
  EUL4_CSUMMARY118979.SET_REFRESH_LOG(TEMPL_SDO_ID);
  EUL4_CSUMMARY118979.ENABLE_QUERY_REWRITE(MATVIEW_OWNER_SQL_IDENT, MATVIEW_NAME_SQL_IDENT, 118979);
  EUL4_CSUMMARY118979.REFRESH_MV(MATVIEW_OWNER_SQL_IDENT, MATVIEW_NAME_SQL_IDENT, TEMPL_REFRESH_TYPE);
  DECLARE
    LOWERCASE_EXC EXCEPTION;
    PRAGMA EXCEPTION_INIT(LOWERCASE_EXC, -20000);
    EXCVAR INTEGER;
    ROWS_PROCESSED INTEGER;
  BEGIN
      DBMS_DDL.ANALYZE_OBJECT('TABLE',MATVIEW_OWNER, MATVIEW_NAME, 'ESTIMATE', 50000);
      ROWS_PROCESSED := EUL4_CSUMMARY118979.GET_NUM_ROWS(MATVIEW_OWNER, MATVIEW_NAME);
      EUL4_CSUMMARY118979.UPDATE_SUMMARY_ROWS(TEMPL_SDO_ID, ROWS_PROCESSED);
      EXCEPTION
        WHEN LOWERCASE_EXC THEN
          EXCVAR := 1;
        WHEN OTHERS THEN
          RAISE;
  END;
  EXCEPTION
  WHEN OTHERS THEN
    ERR_NUM     := SQLCODE;
    ERR_MESSAGE := SQLERRM;
    ROLLBACK;
    EUL4_CSUMMARY118979.UPDATE_SUMMARY_STATE(TEMPL_SDO_ID,ERR_MESSAGE,ERR_NUM);
END;
/

DROP PROCEDURE CPI.EUL4_PSUMMARY119053;
