DROP PROCEDURE CPI.PRE_COMMIT_C_GIPIS002;

CREATE OR REPLACE PROCEDURE CPI.Pre_Commit_C_Gipis002
   (b240_par_id IN NUMBER) IS    
BEGIN
  DELETE GIPI_WOPEN_POLICY
      WHERE par_id = b240_par_id;
END;
/


