DROP PROCEDURE CPI.WHEN_NEWFORM_INST_B_GIPIS002;

CREATE OR REPLACE PROCEDURE CPI.When_Newform_Inst_B_Gipis002
   (PARAMETER_VAR_VDATE OUT NUMBER) IS    
BEGIN
  FOR C IN (SELECT PARAM_VALUE_N
      FROM GIAC_PARAMETERS
      WHERE PARAM_NAME = 'PROD_TAKE_UP')LOOP
    PARAMETER_VAR_VDATE := C.PARAM_VALUE_N;
 END LOOP; 
END;
/


