DROP TRIGGER CPI."BIN$FN3BR95vO3ngUAB/AQA+cg==$0";

CREATE OR REPLACE TRIGGER CPI."BIN$FN3BR95vO3ngUAB/AQA+cg==$0"
BEFORE INSERT OR UPDATE
ON CPI.BIN$FN3BR95wO3ngUAB/AQA+cg==$0 FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


