DROP TRIGGER CPI."BIN$3s7rLuaZT9e+uLB9ob/KRQ==$0";

CREATE OR REPLACE TRIGGER CPI."BIN$3s7rLuaZT9e+uLB9ob/KRQ==$0"
BEFORE INSERT OR UPDATE
ON CPI.GIAC_CASH_DEP_DTL FOR EACH ROW
DECLARE
BEGIN
  :NEW.USER_ID    := NVL(giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


