CREATE OR REPLACE TRIGGER CPI."BIN$0QyrgRaaTUiXhpeJQaUkxw==$0"
BEFORE INSERT OR UPDATE
ON CPI.GICL_MC_LPS FOR EACH ROW
DECLARE
BEGIN
  :NEW.USER_ID    := NVL(giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/

DROP TRIGGER CPI."BIN$0QyrgRaaTUiXhpeJQaUkxw==$0";