DROP TRIGGER CPI.BINDER_PERIL_PRINT_HIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.BINDER_PERIL_PRINT_HIST_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIRI_BINDER_PERIL_PRINT_HIST FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id  := USER;
  :NEW.last_update := SYSDATE;
END;
/


