DROP TRIGGER CPI.BOND_SEQ_HIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.BOND_SEQ_HIST_TBXIU
    BEFORE INSERT OR UPDATE
   ON CPI.GIPI_BOND_SEQ_HIST    FOR EACH ROW
BEGIN
    :NEW.user_id := NVL(giis_users_pkg.app_user, USER);
    :NEW.last_update    := SYSDATE;
END;
/


