DROP TRIGGER CPI.BOND_SEQ_TBXIU;

CREATE OR REPLACE TRIGGER CPI.BOND_SEQ_TBXIU
    BEFORE INSERT OR UPDATE
   ON CPI.GIIS_BOND_SEQ    FOR EACH ROW
BEGIN
    :NEW.user_id := NVL(giis_users_pkg.app_user, USER);
    :NEW.last_update    := SYSDATE;
END;
/


