DROP TRIGGER CPI.CHECK_NO_TBXIU;

CREATE OR REPLACE TRIGGER CPI.CHECK_NO_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIAC_CHECK_NO FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     :=  NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update :=  SYSDATE;
END;
/


