DROP TRIGGER CPI.COC_SERIAL_NO;

CREATE OR REPLACE TRIGGER CPI.COC_SERIAL_NO
BEFORE INSERT OR UPDATE
ON CPI.GIIS_COC_SERIAL_NO FOR EACH ROW
DECLARE
BEGIN
  DECLARE
    BEGIN
      :NEW.user_id     :=  NVL (giis_users_pkg.app_user, USER);
      :NEW.last_update :=  SYSDATE;
    END;
END;
/


