DROP TRIGGER CPI.COLLATERAL_PAR_TBXIX;

CREATE OR REPLACE TRIGGER CPI.COLLATERAL_PAR_TBXIX
BEFORE INSERT
ON CPI.GIPI_COLLATERAL_PAR FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    SELECT   collateral_par_coll_id_seq.nextval
      INTO   :new.coll_par_id
      FROM   dual;
  END;
END;
/


