DROP TRIGGER CPI.COLLATERAL_TYPE_TBXIU;

CREATE OR REPLACE TRIGGER CPI.COLLATERAL_TYPE_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_COLLATERAL_TYPE FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


