DROP TRIGGER CPI.CURRENCY_INSUPD_TBIUX;

CREATE OR REPLACE TRIGGER CPI.CURRENCY_INSUPD_TBIUX
BEFORE INSERT OR UPDATE
ON CPI.GIIS_CURRENCY FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


