DROP TRIGGER CPI.DOCUMENT_COLUMNS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.DOCUMENT_COLUMNS_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_DOCUMENT_COLUMNS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


