DROP TRIGGER CPI.FIREITEM_TBXXU;

CREATE OR REPLACE TRIGGER CPI.FIREITEM_TBXXU
BEFORE UPDATE
ON CPI.GIPI_FIREITEM FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


