DROP TRIGGER CPI.GIAC_OR_PREF_TBXIU;

CREATE OR REPLACE TRIGGER CPI.giac_or_pref_tbxiu
  BEFORE INSERT OR UPDATE ON CPI.GIAC_OR_PREF FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


