DROP TRIGGER CPI.GIAC_CHK_DISBURSEMENT_TAXUX;

CREATE OR REPLACE TRIGGER CPI.GIAC_CHK_DISBURSEMENT_TAXUX
   AFTER UPDATE OF CHECK_PREF_SUF, CHECK_NO ON CPI.GIAC_CHK_DISBURSEMENT    FOR EACH ROW
DECLARE
BEGIN
IF :OLD.check_no IS NOT NULL AND :NEW.CHECK_NO IS NOT NULL THEN
   INSERT INTO GIAC_CHECK_NO_HIST
   VALUES (:OLD.GACC_TRAN_ID, :OLD.CHECK_PREF_SUF, :OLD.CHECK_NO,:NEW.CHECK_PREF_SUF, :NEW.CHECK_NO, NVL (giis_users_pkg.app_user, USER), SYSDATE);
END IF;
END;
/


