DROP TRIGGER CPI.GIAC_WHOLDING_TAXES_TBXIU;

CREATE OR REPLACE TRIGGER CPI.giac_wholding_taxes_tbxiu
BEFORE INSERT OR UPDATE
ON CPI.GIAC_WHOLDING_TAXES FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
    :NEW.last_update := SYSDATE;
  END;
END;
/


