DROP TRIGGER CPI.GIAC_CASH_DEP_DTL_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIAC_CASH_DEP_DTL_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIAC_CASH_DEP_DTL FOR EACH ROW
BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
END;
/


