DROP TRIGGER CPI.GIAC_FUNCTION_COLUMNS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIAC_FUNCTION_COLUMNS_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIAC_FUNCTION_COLUMNS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


