DROP TRIGGER CPI.GIAC_LOSS_RI_COLLNS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.giac_loss_ri_collns_tbxiu
BEFORE INSERT OR UPDATE
ON CPI.GIAC_LOSS_RI_COLLNS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


