DROP TRIGGER CPI.GIAC_REPORT_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIAC_REPORT_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIAC_REPORT_COLUMN_TYPE FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


