DROP TRIGGER CPI.GIAC_OR_PREF_TBXIX;

CREATE OR REPLACE TRIGGER CPI.GIAC_OR_PREF_TBXIX 
BEFORE INSERT 
ON CPI.GIAC_OR_PREF 
FOR EACH ROW
DECLARE 
BEGIN 
  :NEW.fund_cd := giacp.v('FUND_CD'); 
END;
/


