DROP TRIGGER CPI.GIAC_BANK_BOOK_TRAN_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIAC_BANK_BOOK_TRAN_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIAC_BANK_BOOK_TRAN FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


