DROP TRIGGER CPI.GIAC_CPC_CLM_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIAC_CPC_CLM_TBXIU 
BEFORE INSERT OR UPDATE 
ON CPI.GIAC_CPC_CLM_INCURRED_DTL 
FOR EACH ROW
DECLARE 
BEGIN 
  DECLARE 
    BEGIN 
      :NEW.user_id     :=  USER; 
      :NEW.last_update :=  SYSDATE; 
    END; 
END;
/


