DROP TRIGGER CPI.GIAC_TB_SUMMARY_TBXIU;

CREATE OR REPLACE TRIGGER CPI.giac_tb_summary_tbxiu
BEFORE INSERT OR UPDATE
ON CPI.GIAC_TRIAL_BALANCE_SUMMARY FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
    :NEW.last_update := SYSDATE;
  END;
END;
/


