DROP TRIGGER CPI.GIAC_CURRENCY_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIAC_CURRENCY_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIAC_CURRENCY FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
     :NEW.user_ID  := NVL (giis_users_pkg.app_user, USER);
     :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


