DROP TRIGGER CPI.GIAC_DEFERRED_PROCEDURES_TBUIX;

CREATE OR REPLACE TRIGGER CPI.GIAC_DEFERRED_PROCEDURES_TBUIX
BEFORE INSERT OR UPDATE
ON CPI.GIAC_DEFERRED_PROCEDURES FOR EACH ROW
BEGIN
  BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


