DROP TRIGGER CPI.GICL_CLM_LOSS_EXP_RIDS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_CLM_LOSS_EXP_RIDS_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GICL_LOSS_EXP_RIDS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


