DROP TRIGGER CPI.GICL_CLM_ITEM_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_CLM_ITEM_TBXIU 
BEFORE INSERT OR UPDATE 
ON CPI.GICL_CLM_ITEM 
FOR EACH ROW
DECLARE 
BEGIN 
:NEW.grouped_item_no := NVL(:NEW.grouped_item_no,0); 
END;
/


