DROP TRIGGER CPI.GICL_RECOVERY_RIDS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_RECOVERY_RIDS_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GICL_RECOVERY_RIDS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


