DROP TRIGGER CPI.GICL_REPLACE_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_REPLACE_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GICL_REPLACE FOR EACH ROW
DECLARE
  x NUMBER;
BEGIN
 IF INSERTING THEN
  SELECT replace_id_SEq.NEXTVAL
    INTO x
    FROM DUAL;
  :NEW.replace_id := x;
 END IF;

  :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


