DROP TRIGGER CPI.GICL_MC_PART_COST_HIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_MC_PART_COST_HIST_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GICL_MC_PART_COST_HIST FOR EACH ROW
BEGIN
  :NEW.user_id   := NVL (giis_users_pkg.app_user, USER);
END;
/


