DROP TRIGGER CPI.GICL_MOTOR_CAR_DTL_TADIU;

CREATE OR REPLACE TRIGGER CPI.GICL_MOTOR_CAR_DTL_TADIU
AFTER DELETE OR INSERT OR UPDATE OF plate_no ON CPI.GICL_MOTOR_CAR_DTL REFERENCING OLD AS luma NEW AS bago
FOR EACH ROW
BEGIN
IF UPDATING OR INSERTING THEN
UPDATE GICL_CLAIMS
SET plate_no = :bago.plate_no
WHERE claim_id = :bago.claim_id;
ELSIF DELETING THEN
UPDATE GICL_CLAIMS
SET plate_no = NULL
WHERE claim_id = :luma.claim_id;
END IF;
END;
/


