DROP TRIGGER CPI.GICL_TAKE_UP_HIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_TAKE_UP_HIST_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GICL_TAKE_UP_HIST FOR EACH ROW
DECLARE
BEGIN
  :NEW.grouped_item_no    := nvl(:NEW.grouped_item_no,0);
END;
/


