DROP TRIGGER CPI.GICL_MC_PART_COST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_MC_PART_COST_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GICL_MC_PART_COST FOR EACH ROW
BEGIN
  :NEW.user_id   := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


