DROP TRIGGER CPI.GICL_MC_DEPRECIATION_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GICL_MC_DEPRECIATION_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GICL_MC_DEPRECIATION FOR EACH ROW
BEGIN
 :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
 :NEW.LAST_UPDATE := SYSDATE;
END;
/


