DROP TRIGGER CPI.GICL_ADV_LINE_AMT_TBIUX;

CREATE OR REPLACE TRIGGER CPI.GICL_ADV_LINE_AMT_TBIUX
  BEFORE INSERT OR UPDATE ON CPI.GICL_ADV_LINE_AMT FOR EACH ROW
BEGIN
 IF INSERTING THEN
  :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
 ELSIF UPDATING THEN
  :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
 END IF;
END;
/


