DROP TRIGGER CPI.GICL_MORTGAGEE_TBIXX;

CREATE OR REPLACE TRIGGER CPI.GICL_MORTGAGEE_TBIXX
BEFORE INSERT OR UPDATE
ON CPI.GICL_MORTGAGEE FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


