DROP TRIGGER CPI.GIIS_PERIL_GROUP_TBIUX;

CREATE OR REPLACE TRIGGER CPI.GIIS_PERIL_GROUP_TBIUX
BEFORE INSERT OR UPDATE
ON CPI.GIIS_PERIL_GROUP FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


