DROP TRIGGER CPI.GIIS_EVENT_MOD_USERS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_EVENT_MOD_USERS_TBXIU
       BEFORE INSERT OR UPDATE
       ON CPI.GIIS_EVENT_MOD_USERS        FOR EACH ROW
DECLARE
      BEGIN
        :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
        :NEW.last_update := SYSDATE;
      END;
/


