DROP TRIGGER CPI.GIIS_TAKEUP_TERM_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_TAKEUP_TERM_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GIIS_TAKEUP_TERM FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := sysdate;
END;
/


