DROP TRIGGER CPI.GIIS_NON_RENEW_REASON_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_NON_RENEW_REASON_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GIIS_NON_RENEW_REASON FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


