DROP TRIGGER CPI.GIIS_ISSOURCE_PLACE_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_ISSOURCE_PLACE_TBXIU
  BEFORE INSERT OR UPDATE ON CPI.GIIS_ISSOURCE_PLACE FOR EACH ROW
DECLARE
BEGIN
  :new.user_id    := NVL (giis_users_pkg.app_user, USER);
  :new.last_update := SYSDATE;
END;
/


