DROP TRIGGER CPI.GIIS_CONTROL_TYPE_T;

CREATE OR REPLACE TRIGGER CPI.GIIS_CONTROL_TYPE_T
BEFORE INSERT OR UPDATE
ON CPI.GIIS_CONTROL_TYPE FOR EACH ROW
DECLARE
BEGIN
   :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
   :NEW.last_update := SYSDATE;
END;
/


