DROP TRIGGER CPI.GIIS_GENIN_INFO_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_GENIN_INFO_TBXIU
 BEFORE INSERT OR UPDATE ON CPI.GIIS_GENIN_INFO  FOR EACH ROW
DECLARE
 BEGIN
  :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
 END;
/


