DROP TRIGGER CPI.GIIS_LOSS_TAXES_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_LOSS_TAXES_TBXIU
--CREATED BY JHEFF
BEFORE INSERT OR UPDATE
ON CPI.GIIS_LOSS_TAXES REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


