DROP TRIGGER CPI.GIIS_ASSURED_GROUP_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_ASSURED_GROUP_TBXIU
  BEFORE INSERT OR UPDATE ON CPI.GIIS_ASSURED_GROUP FOR EACH ROW
DECLARE
BEGIN
  :new.user_id    := NVL (giis_users_pkg.app_user, USER);
  :new.last_update := SYSDATE;
END;
/


