DROP TRIGGER CPI.GIIS_BINDER_STATUS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_BINDER_STATUS_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GIIS_BINDER_STATUS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


