DROP TRIGGER CPI.GIIS_PERIL_TARIFF_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_PERIL_TARIFF_TBXIU
   BEFORE INSERT OR UPDATE ON CPI.GIIS_PERIL_TARIFF FOR EACH ROW
DECLARE
BEGIN
   :new.user_id  := NVL (giis_users_pkg.app_user, USER);
   :new.last_update := sysdate;
END;
/


