DROP TRIGGER CPI.GIIS_DOCUMENT_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_DOCUMENT_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_DOCUMENT FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id  := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


