DROP TRIGGER CPI.GIIS_ADHOC_PARAMETERS;

CREATE OR REPLACE TRIGGER CPI.GIIS_ADHOC_PARAMETERS
BEFORE INSERT OR UPDATE
ON CPI.GIIS_ADHOC_PARAMETERS FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


