DROP TRIGGER CPI.GIIS_MODULES_USER_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_MODULES_USER_TBXIU
  BEFORE INSERT OR UPDATE ON CPI.GIIS_MODULES_USER FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


