DROP TRIGGER CPI.GIIS_POSTING_LIMIT_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIIS_POSTING_LIMIT_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GIIS_POSTING_LIMIT FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID      := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE  := SYSDATE;
END;
/


