DROP TRIGGER CPI.GIPI_WOPEN_LIAB_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_WOPEN_LIAB_TBXIU
BEFORE INSERT
ON CPI.GIPI_WOPEN_LIAB FOR EACH ROW
DECLARE
BEGIN
  :NEW.CREATE_user := NVL (giis_users_pkg.app_user, USER);
  :NEW.CREATE_DATE := SYSDATE;
END;
/


