DROP TRIGGER CPI.GIPI_PARLIST_DEL_REC_TBXIX;

CREATE OR REPLACE TRIGGER CPI.GIPI_PARLIST_DEL_REC_TBXIX
BEFORE INSERT
ON CPI.GIPI_PARLIST_DEL_REC FOR EACH ROW
DECLARE
BEGIN
    DECLARE
    BEGIN
        :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
        :NEW.last_update := SYSDATE;
    END;
END;
/


