DROP TRIGGER CPI.GIPI_WOPEN_CARGO_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_WOPEN_CARGO_TBXIU
BEFORE INSERT
ON CPI.GIPI_WOPEN_CARGO FOR EACH ROW
DECLARE
BEGIN
  :NEW.CREATE_user := NVL (giis_users_pkg.app_user, USER);
  :NEW.CREATE_DATE := SYSDATE;
  :NEW.user_ID      := NVL (giis_users_pkg.app_user, USER); --added by reymon 02212013
  :NEW.LAST_UPDATE  := SYSDATE; --added by reymon 02212013
END;
/


