DROP TRIGGER CPI.GIPI_LOAD_HIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_LOAD_HIST_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_LOAD_HIST FOR EACH ROW
DECLARE
BEGIN
     DECLARE
     BEGIN
         :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
         :NEW.last_update := SYSDATE;
     END;
END;
/


