DROP TRIGGER CPI.GIPI_UPLOAD_BENEFICIARY_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_UPLOAD_BENEFICIARY_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_UPLOAD_BENEFICIARY FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


