DROP TRIGGER CPI.GIPI_WPICTURES_TBXIU2;

CREATE OR REPLACE TRIGGER CPI.GIPI_WPICTURES_TBXIU2
BEFORE UPDATE
ON CPI.GIPI_WPICTURES FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


