DROP TRIGGER CPI.GIPI_WVES_AIR_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_WVES_AIR_TBXIU
BEFORE INSERT
ON CPI.GIPI_WVES_AIR FOR EACH ROW
DECLARE
BEGIN
  :NEW.CREATE_user := NVL (giis_users_pkg.app_user, USER);
  :NEW.CREATE_DATE := SYSDATE;
END;
/


