DROP TRIGGER CPI.GIPI_PACK_WPOLNREP_TAXDX;

CREATE OR REPLACE TRIGGER CPI.GIPI_PACK_WPOLNREP_TAXDX
BEFORE DELETE
ON CPI.GIPI_PACK_WPOLNREP FOR EACH ROW
DECLARE
BEGIN

DELETE FROM GIPI_WPOLNREP
 WHERE PAR_ID IN (SELECT PAR_ID FROM GIPI_PARLIST
                  WHERE PACK_PAR_ID = :OLD.PACK_PAR_ID)
   AND OLD_POLICY_ID IN (SELECT policy_id FROM gipi_polbasic
                          WHERE pack_policy_id = :OLD.old_pack_policy_id);   

END;
/


