DROP TRIGGER CPI.GIPI_INV_TAX_PRINT_HIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_INV_TAX_PRINT_HIST_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_INV_TAX_PRINT_HIST FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id  := USER;
  :NEW.last_update := SYSDATE;
END;
/


