DROP TRIGGER CPI.GIPI_MC_ERROR_LOG_T;

CREATE OR REPLACE TRIGGER CPI.GIPI_MC_ERROR_LOG_T
BEFORE INSERT OR UPDATE
ON CPI.GIPI_MC_ERROR_LOG FOR EACH ROW
DECLARE
BEGIN
   :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
   :NEW.last_update := SYSDATE;
END;
/


