DROP TRIGGER CPI.GIPI_WPICTURES_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_WPICTURES_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_WPICTURES FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


