DROP TRIGGER CPI.GIPI_UPLOAD_ITMPERIL_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_UPLOAD_ITMPERIL_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_UPLOAD_ITMPERIL FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
      END;
/


