DROP TRIGGER CPI.GIPI_UWREPORTS_DIST_EXT_TRG;

CREATE OR REPLACE TRIGGER CPI.GIPI_UWREPORTS_DIST_EXT_TRG
BEFORE INSERT OR UPDATE
ON CPI.GIPI_UWREPORTS_DIST_EXT FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER); --USER;
    :NEW.last_update := SYSDATE;
  END;
END;
/


