DROP TRIGGER CPI.GIPI_QUOTE_DEDUCTIBLES_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIPI_QUOTE_DEDUCTIBLES_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_QUOTE_DEDUCTIBLES FOR EACH ROW
DECLARE
BEGIN
     DECLARE
     BEGIN
          :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
          :NEW.last_update := sysdate;
     END;
END;
/


