DROP TRIGGER CPI.GIRI_PACK_BINDER_HDR_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIRI_PACK_BINDER_HDR_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIRI_PACK_BINDER_HDR FOR EACH ROW
DECLARE
BEGIN
IF NVL (giis_users_pkg.app_user, USER) <> 'CPI' THEN
 :NEW.user_id   :=NVL (giis_users_pkg.app_user, USER);
 :NEW.last_update  :=SYSDATE;
END IF;
END;
/


