DROP TRIGGER CPI.GIRI_PACK_BINDER_DTL_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIRI_PACK_BINDER_DTL_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIRI_PACK_BINDER_DTL FOR EACH ROW
DECLARE
BEGIN
 :NEW.user_id   :=NVL (giis_users_pkg.app_user, USER);
 :NEW.last_update  :=SYSDATE;
END;
/


