DROP TRIGGER CPI.GIRI_GROUP_BINDREL_REV_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIRI_GROUP_BINDREL_REV_TBXIU
before INSERT or UPDATE
ON CPI.GIRI_GROUP_BINDREL_REV for each row
DECLARE
BEGIN
 :new.user_id   :=NVL (giis_users_pkg.app_user, USER);
 :new.last_update  :=SYSDATE;
END;
/


