DROP TRIGGER CPI.GISM_RECIPIENT_GROUP_TBIXX;

CREATE OR REPLACE TRIGGER CPI.GISM_RECIPIENT_GROUP_TBIXX 
BEFORE INSERT 
ON CPI.GISM_RECIPIENT_GROUP 
FOR EACH ROW
DECLARE 
BEGIN 
  FOR rec IN (SELECT GISM_GROUP_CD_s.NEXTVAL seq 
  	  	  	 	FROM dual) 
  LOOP 
    :NEW.GROUP_CD := rec.seq; 
    EXIT; 
  END LOOP; 
END;
/


