DROP TRIGGER CPI.GISM_ERROR_MESSAGE_TBIXX;

CREATE OR REPLACE TRIGGER CPI.GISM_ERROR_MESSAGE_TBIXX 
BEFORE INSERT 
ON CPI.GISM_ERROR_MESSAGE 
FOR EACH ROW
DECLARE 
BEGIN 
  FOR rec IN (SELECT gism_error_message_tran_id_s.NEXTVAL seq 
  	  	  	 	FROM dual) 
  LOOP 
    :NEW.tran_id := rec.seq; 
    EXIT; 
  END LOOP; 
END;
/


