DROP TRIGGER CPI.GISM_ERR_TBIUX;

CREATE OR REPLACE TRIGGER CPI.GISM_ERR_TBIUX
BEFORE INSERT OR UPDATE
ON CPI.GISM_ERR FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


