DROP TRIGGER CPI.GISM_MESSAGE_TEMPLATE_TBIXX;

CREATE OR REPLACE TRIGGER CPI.GISM_MESSAGE_TEMPLATE_TBIXX
BEFORE INSERT
ON CPI.GISM_MESSAGE_TEMPLATE FOR EACH ROW
DECLARE
BEGIN
    :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
    :NEW.last_update := SYSDATE;
END;
/


