DROP TRIGGER CPI.GIUW_POL_DIST_TBXIU;

CREATE OR REPLACE TRIGGER CPI.GIUW_POL_DIST_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIUW_POL_DIST FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPD_DATE := sysdate;
  END;
END;
/


