DROP TRIGGER CPI.GRPD_TBIUX;

CREATE OR REPLACE TRIGGER CPI.GRPD_TBIUX
BEFORE INSERT OR UPDATE
ON CPI.GIPI_RISK_PROFILE_DTL FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


