DROP TRIGGER CPI.INSP_DATA_TBXIU;

CREATE OR REPLACE TRIGGER CPI.INSP_DATA_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_INSP_DATA FOR EACH ROW
DECLARE
BEGIN
DECLARE
BEGIN
:NEW.user_id := NVL (giis_users_pkg.app_user, USER);
:NEW.last_update := sysdate;
END;
END;
/


