DROP TRIGGER CPI.LOSS_EXP_STAT_TBIUX;

CREATE OR REPLACE TRIGGER CPI.LOSS_EXP_STAT_TBIUX
BEFORE INSERT OR UPDATE
ON CPI.GICL_LE_STAT FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


