DROP TRIGGER CPI.MC_COLOR_TBXIU;

CREATE OR REPLACE TRIGGER CPI.MC_COLOR_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_MC_COLOR FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


