DROP TRIGGER CPI.MC_ENG_SERIES_TBXIU;

CREATE OR REPLACE TRIGGER CPI.MC_ENG_SERIES_TBXIU
  BEFORE INSERT OR UPDATE ON CPI.GIIS_MC_ENG_SERIES FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
END;
/


