DROP TRIGGER CPI.MC_MODEL_YEAR_TBIUX;

CREATE OR REPLACE TRIGGER CPI.MC_MODEL_YEAR_TBIUX
BEFORE INSERT OR UPDATE
ON CPI.GIIS_MC_MODEL_YEAR FOR EACH ROW
DECLARE
BEGIN
   :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
   :NEW.LAST_UPDATE := SYSDATE;
END;
/


