DROP TRIGGER CPI.MC_QUOTE_TBXIU;

CREATE OR REPLACE TRIGGER CPI.MC_QUOTE_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_QUOTE_ITEM_MC FOR EACH ROW
DECLARE
BEGIN
     DECLARE
     BEGIN
         :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
         :NEW.last_update := SYSDATE;
     END;
END;
/


