DROP TRIGGER CPI.NOTARY_PUBLIC_TBXIU;

CREATE OR REPLACE TRIGGER CPI.NOTARY_PUBLIC_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_NOTARY_PUBLIC FOR EACH ROW
DECLARE
BEGIN
  DECLARE
   BEGIN
     IF INSERTING THEN
       SELECT NOTARY_PUBLIC_NP_ID_S.NEXTVAL
         INTO :NEW.NP_NO
         FROM DUAL;
     END IF;
     :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
     :NEW.LAST_UPDATE := SYSDATE;
   END;
END;
/


