DROP TRIGGER CPI.PACK_RN_NO_TBXIU;

CREATE OR REPLACE TRIGGER CPI.PACK_RN_NO_TBXIU
BEFORE INSERT OR UPDATE ON CPI.GIEX_PACK_RN_NO FOR EACH ROW
DECLARE
BEGIN
   DECLARE
   BEGIN
      :NEW.user_ID      := NVL (giis_users_pkg.app_user, USER);
      :NEW.LAST_UPDATE  := SYSDATE;
   END;
END;
/


