DROP TRIGGER CPI.PACKAGE_BENEFIT_DTL;

CREATE OR REPLACE TRIGGER CPI.PACKAGE_BENEFIT_DTL
BEFORE INSERT OR UPDATE
ON CPI.GIIS_PACKAGE_BENEFIT_DTL FOR EACH ROW
DECLARE
BEGIN
  DECLARE
    BEGIN
      :NEW.user_id     :=  NVL (giis_users_pkg.app_user, USER);
      :NEW.last_update :=  SYSDATE;
    END;
END;
/


