DROP TRIGGER CPI.PAYEE_CLASS_TBXIU;

CREATE OR REPLACE TRIGGER CPI.PAYEE_CLASS_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_PAYEE_CLASS FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
   :NEW.user_ID     :=  NVL (giis_users_pkg.app_user, USER);
   :NEW.LAST_UPDATE :=  SYSDATE;
  END;

END;
/


