DROP TRIGGER CPI.QUOTE_EN_ITEM_TBXIU;

CREATE OR REPLACE TRIGGER CPI.QUOTE_EN_ITEM_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_QUOTE_EN_ITEM FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     :=  NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update :=  SYSDATE;
END;
/


