DROP TRIGGER CPI.QUOTE_INV_SEQ_TBXIU;

CREATE OR REPLACE TRIGGER CPI.QUOTE_INV_SEQ_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_QUOTE_INV_SEQ FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_id     :=  NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update :=  SYSDATE;
END;
/


