DROP TRIGGER CPI.RISK_LOSS_ITEM;

CREATE OR REPLACE TRIGGER CPI.RISK_LOSS_ITEM
BEFORE INSERT OR UPDATE
ON CPI.GIPI_RISK_LOSS_PROFILE_ITEM FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.USER_ID    := USER;
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


