DROP TRIGGER CPI.ROLLIE_RISK;

CREATE OR REPLACE TRIGGER CPI.ROLLIE_RISK
BEFORE INSERT OR UPDATE
ON CPI.GIPI_RISK_PROFILE_ITEM FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


