DROP TRIGGER CPI.TRG1_GIIS_POST_ERROR_LOG;

CREATE OR REPLACE TRIGGER CPI.TRG1_GIIS_POST_ERROR_LOG
BEFORE INSERT OR UPDATE
ON CPI.GIIS_POST_ERROR_LOG FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := sysdate;
  END;
END;
/


