DROP TRIGGER CPI.TRG1_LOST_BID;

CREATE OR REPLACE TRIGGER CPI.TRG1_LOST_BID
BEFORE INSERT OR UPDATE
ON CPI.GIIS_LOST_BID FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
       :NEW.last_update := SYSDATE;
  END;
END;
/


