DROP TRIGGER CPI.TRG1_USER_LINE;

CREATE OR REPLACE TRIGGER CPI.TRG1_USER_LINE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_USER_LINE FOR EACH ROW
BEGIN
    :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
    :NEW.last_update := SYSDATE;
END;
/


