DROP TRIGGER CPI.TRG1_CA_TRTY_TYPE;

CREATE OR REPLACE TRIGGER CPI.TRG1_CA_TRTY_TYPE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_CA_TRTY_TYPE REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


