DROP TRIGGER CPI.TRG1_CO_INTRMDRY_TYPES;

CREATE OR REPLACE TRIGGER CPI.TRG1_CO_INTRMDRY_TYPES
BEFORE INSERT OR UPDATE
ON CPI.GIIS_CO_INTRMDRY_TYPES FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


