DROP TRIGGER CPI.TRG1_INTMDRY_COMRT;

CREATE OR REPLACE TRIGGER CPI.TRG1_INTMDRY_COMRT
BEFORE INSERT OR UPDATE
ON CPI.GIIS_INTMDRY_COMRT FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
  :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


