DROP TRIGGER CPI.TRG1_RN_SEQ;

CREATE OR REPLACE TRIGGER CPI.TRG1_RN_SEQ
BEFORE INSERT OR UPDATE ON CPI.GIIS_RN_SEQ FOR EACH ROW
DECLARE
BEGIN
   DECLARE
   BEGIN
      :NEW.user_ID      := NVL (giis_users_pkg.app_user, USER);
      :NEW.LAST_UPDATE  := SYSDATE;
   END;
END;
/


