DROP TRIGGER CPI.TRG1_BANK_ACCOUNTS;

CREATE OR REPLACE TRIGGER CPI.TRG1_BANK_ACCOUNTS
BEFORE INSERT OR UPDATE
ON CPI.GIAC_BANK_ACCOUNTS FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


