DROP TRIGGER CPI.TRG1_RI_TYPE_DOCS;

CREATE OR REPLACE TRIGGER CPI.TRG1_RI_TYPE_DOCS
BEFORE INSERT OR UPDATE
ON CPI.GIIS_RI_TYPE_DOCS FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


