DROP TRIGGER CPI.TRG1_USERS;

CREATE OR REPLACE TRIGGER CPI.TRG1_USERS
BEFORE INSERT OR UPDATE
ON CPI.GIAC_USERS FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
    :NEW.TRAN_user_ID := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


