DROP TRIGGER CPI.TRG1_RI_STATUS;

CREATE OR REPLACE TRIGGER CPI.TRG1_RI_STATUS
BEFORE INSERT OR UPDATE
ON CPI.GIIS_RI_STATUS FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


