DROP TRIGGER CPI.TRG1_TARIFF_ZONE;

CREATE OR REPLACE TRIGGER CPI.TRG1_TARIFF_ZONE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_TARIFF_ZONE FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


