DROP TRIGGER CPI.TRG1_DEDUCTIBLE_DESC;

CREATE OR REPLACE TRIGGER CPI.TRG1_DEDUCTIBLE_DESC
BEFORE INSERT OR UPDATE
ON CPI.GIIS_DEDUCTIBLE_DESC FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;

END;
/


