DROP TRIGGER CPI.TRG1_ALIAS;

CREATE OR REPLACE TRIGGER CPI.TRG1_ALIAS
BEFORE INSERT OR UPDATE
ON CPI.GIIS_ALIAS FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
     :NEW.UPDATED_BY  := NVL (giis_users_pkg.app_user, USER);
     :NEW.UPDATE_DATE := SYSDATE;
  END;
END;
/


