DROP TRIGGER CPI.TRG1_MC_PERIL_RATE;

CREATE OR REPLACE TRIGGER CPI.TRG1_MC_PERIL_RATE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_MC_PERIL_RATE FOR EACH ROW
DECLARE
BEGIN
  BEGIN
       :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


