DROP TRIGGER CPI.TRG1_TRTY_PANEL;

CREATE OR REPLACE TRIGGER CPI.TRG1_TRTY_PANEL
BEFORE INSERT OR UPDATE
ON CPI.GIIS_TRTY_PANEL FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


