DROP TRIGGER CPI.TRG1_INTMDRY_TYPE_RT;

CREATE OR REPLACE TRIGGER CPI.TRG1_INTMDRY_TYPE_RT
BEFORE INSERT OR UPDATE
ON CPI.GIIS_INTMDRY_TYPE_RT FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
  :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
  :NEW.last_update := SYSDATE;
  END;
END;
/


