DROP TRIGGER CPI.TRG1_MC_SUBLINE_TYPE;

CREATE OR REPLACE TRIGGER CPI.TRG1_MC_SUBLINE_TYPE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_MC_SUBLINE_TYPE FOR EACH ROW
DECLARE
BEGIN
    :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
END;
/


