DROP TRIGGER CPI.TRG1_BOND_CLASS_CLAUSE;

CREATE OR REPLACE TRIGGER CPI.TRG1_BOND_CLASS_CLAUSE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_BOND_CLASS_CLAUSE FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
     :NEW.user_ID  := NVL (giis_users_pkg.app_user, USER);
     :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


