DROP TRIGGER CPI.TRG1_SECTION_OR_HAZARD;

CREATE OR REPLACE TRIGGER CPI.TRG1_SECTION_OR_HAZARD
BEFORE INSERT OR UPDATE
ON CPI.GIIS_SECTION_OR_HAZARD FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  begin
    :new.user_id := NVL (giis_users_pkg.app_user, USER);
    :new.last_update := sysdate;
  end;
END;
/


