DROP TRIGGER CPI.TRG1_ENG_PRINCIPAL;

CREATE OR REPLACE TRIGGER CPI.TRG1_ENG_PRINCIPAL
BEFORE INSERT OR UPDATE
ON CPI.GIIS_ENG_PRINCIPAL FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
  :NEW.user_ID := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


