DROP TRIGGER CPI.TRG1_REPORTS_AGING;

CREATE OR REPLACE TRIGGER CPI.TRG1_REPORTS_AGING
BEFORE INSERT OR UPDATE
ON CPI.GIIS_REPORT_AGING FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.user_id    := NVL (giis_users_pkg.app_user, USER);
       :NEW.last_update := SYSDATE;
  END;
END;
/


