DROP TRIGGER CPI.TRG1_TRANSACTION;

CREATE OR REPLACE TRIGGER CPI.TRG1_TRANSACTION
BEFORE INSERT OR UPDATE
ON CPI.GIIS_TRANSACTION FOR EACH ROW
BEGIN
    :NEW.user_id := NVL (giis_users_pkg.app_user, USER);
    :NEW.last_update := SYSDATE;
END;
/


