DROP TRIGGER CPI.TRG1_TAX_RANGE;

CREATE OR REPLACE TRIGGER CPI.TRG1_TAX_RANGE
BEFORE INSERT OR UPDATE
ON CPI.GIIS_TAX_RANGE FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
       :NEW.USER_ID    := NVL (giis_users_pkg.app_user, USER);
       :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


