DROP TRIGGER CPI.TRG1_FRPS_SEQ;

CREATE OR REPLACE TRIGGER CPI.TRG1_FRPS_SEQ
BEFORE INSERT OR DELETE
ON CPI.GIIS_FRPS_SEQ FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
     :NEW.user_ID  := NVL (giis_users_pkg.app_user, USER);
     :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


