DROP TRIGGER CPI.TRG1_PRIN_SIGNTRY;

CREATE OR REPLACE TRIGGER CPI.TRG1_PRIN_SIGNTRY
BEFORE INSERT OR UPDATE
ON CPI.GIIS_PRIN_SIGNTRY FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
     :NEW.user_ID  := NVL (giis_users_pkg.app_user, USER);
     :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


