DROP TRIGGER CPI.TRG_PROD_BUDGET;

CREATE OR REPLACE TRIGGER CPI.TRG_PROD_BUDGET
BEFORE INSERT OR UPDATE
ON CPI.GIAC_PROD_BUDGET FOR EACH ROW
DECLARE
BEGIN
  :NEW.user_ID    := NVL (giis_users_pkg.app_user, USER);
  :NEW.LAST_UPDATE := SYSDATE;
END;
/


