DROP TRIGGER CPI.TRG_DCB_USER;

CREATE OR REPLACE TRIGGER CPI.TRG_DCB_USER
BEFORE INSERT OR UPDATE
ON CPI.GIAC_DCB_USERS FOR EACH ROW
BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
END;
/


