DROP TRIGGER CPI.TRG_GIAC_OUCS;

CREATE OR REPLACE TRIGGER CPI.TRG_GIAC_OUCS
BEFORE INSERT OR UPDATE
ON CPI.GIAC_OUCS FOR EACH ROW
BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
END;
/


