DROP TRIGGER CPI.TRG_USERS_SEC_INSERT;

CREATE OR REPLACE TRIGGER CPI.TRG_USERS_SEC_INSERT
AFTER INSERT ON CPI.GIIS_USERS FOR EACH ROW
BEGIN
    INSERT INTO users VALUES(:NEW.user_id, :NEW.password, 1);
    INSERT INTO authorities VALUES(:NEW.user_id, 'ROLE_user'); 
END;
/


