DROP TRIGGER CPI.TRG_ADJUSTER;

CREATE OR REPLACE TRIGGER CPI.TRG_ADJUSTER
BEFORE INSERT OR UPDATE
ON CPI.GIIS_ADJUSTER FOR EACH ROW
BEGIN
    :NEW.user_ID     := NVL (giis_users_pkg.app_user, USER);
    :NEW.LAST_UPDATE := SYSDATE;
END;
/


