DROP TRIGGER CPI.TYPE_OF_BODY_TBXIU;

CREATE OR REPLACE TRIGGER CPI.TYPE_OF_BODY_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIIS_TYPE_OF_BODY FOR EACH ROW
DECLARE
BEGIN
  DECLARE
  BEGIN
     :NEW.user_ID  :=  NVL (giis_users_pkg.app_user, USER);
     :NEW.LAST_UPDATE := SYSDATE;
  END;
END;
/


