DROP TRIGGER CPI.WPOLGENIN_TBXIU;

CREATE OR REPLACE TRIGGER CPI.WPOLGENIN_TBXIU
BEFORE INSERT OR UPDATE
ON CPI.GIPI_WPOLGENIN FOR EACH ROW
DECLARE
BEGIN
 :NEW.user_id     :=  NVL (giis_users_pkg.app_user, USER);
 :NEW.last_update :=  SYSDATE;
END;
/


