SET SERVEROUTPUT ON 
BEGIN 

    EXECUTE IMMEDIATE 'CREATE INDEX  CPI.DEF_POLICY_NO_IDX2 ON CPI.GIAC_DEFERRED_RI_PREM_CEDE_POL (policy_no)';
    
   
 DBMS_OUTPUT.PUT_LINE('index created');
EXCEPTION 
WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE(SQLERRM || '-' || SQLCODE);
END;
 /