DROP INDEX CPI.GDCU_PK;

CREATE UNIQUE INDEX CPI.GDCU_PK ON CPI.GIAC_DCB_USERS
(GIBR_FUND_CD, GIBR_BRANCH_CD, CASHIER_CD)
LOGGING
TABLESPACE INDEXES
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
